import Head from 'next/head';
// import '../styles/globals.css';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillInstagram,
} from "react-icons/ai";
import avatar from '../public/avatar.png';
import Image from 'next/image';
import Projects from '../components/projects.js';
import Skills from '../components/skills.js';

export default function Home() {


  const downloadFile = () => {
    // using Java Script method to get PDF file
    fetch('Adnan_Shaik_Resume_5.pdf').then(response => {
        response.blob().then(blob => {
            // Creating new object of PDF file
            const fileURL = window.URL.createObjectURL(blob);
            // Setting various property values
            let alink = document.createElement('a');
            alink.href = fileURL;
            alink.download = 'Adnan_Shaik_Resume_5.pdf';
            alink.click();
        })
    })
}
  return (
    <div>
      <Head>
        <title>Adnan Shaik Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-900 px-5 md:px-5 lg:px-10 light:bg-white'>
        <section className=' min-h-screen' >
          <nav className='py-10 mb-12 flex justify-between text-white font-semibold'>
            <h1 className='font-burtons text-2xl text-transparent bg-clip-text
            bg-gradient-to-r from-blue-600 via-green-500 to-indigo-400'>DevelopedByAdnan</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill
                onClick={()=>{
                  setLightMode(!lightMode)
                console.log(lightMode)}}
                className='cursor-pointer text-2xl text-white'
                />
              </li>
              <li>
                <a onClick={downloadFile} className='bg-gradient-to-r from-red-600
               text-white px-4 py-2 border-none rounded-md ml-8   cursor-pointer
               hover:bg-cyan-400'>
                  Resume
                </a>
              </li>
              <li className='cursor-pointer text-xl text-white font-burtons ml-4 '>
                <h2 className='hover:text-[#E52B50]'>
                  <a href='mailto:adnanshaik179@gmail.com'>contact info</a>
                </h2>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 py-10'>
              <h1 className='text-5xl py-2 text-[#E52B50] font-medium md:text-6xl leading-13'>
                Hello I am Adnan Shaik<br/>
                You can call me Adnan!
              </h1>
              <h3 className='text-2xl py-2 font-semibold text-white md:text-3xl'>
                I am a front-end Developer and UX/UI Designer.
              </h3>
              <p className='text-xl py-5 leading-8 font-medium text-teal-500
              max-w-xl mx-auto md:text-xl'>
                Embarking on a Journey to Become a Skilled Developer: 
                Creating Beautiful Websites and Apps with Perseverance and Passion.
              </p>
            <div className='text-5xl flex justify-center gap-16 py-3 
            text-[#E52B50]'>
              <a href='https://www.instagram.com/_adnan179/'>
                <AiFillInstagram className='cursor-pointer transtion ease-in-out delay-150 hover:text-white duration-300'/>
              </a>
              <a href='https://www.linkedin.com/in/adnanshaik179/'>
              <AiFillLinkedin className='cursor-pointer transtion ease-in-out delay-150 hover:text-white duration-300'/>
              </a>
              <a href='https://github.com/adnan179'>
              <AiFillGithub className='cursor-pointer transtion ease-in-out delay-150 hover:text-white duration-300'/>
              </a>
            </div>
            <div className='md:grid md:grid-cols-2 mt-10'>
              <div>
                <h1 className='text-[#E52B50] font-semibold text-5xl float-left mb-5'>About ME</h1>
                <p className='float-left font-medium text-white text-left text-xl leading-8'>
                One of my sweet memories during my second year of college is finding myself in love with websites, how aesthetic they look and how helpful there are for every basic need we have nowadays. 
                Since then I started my web development learning journey and trying to fulfill my hunger for becoming a developer. 
                I am a student, pursuing my B. Tech fourth year in computer science specialized in cyber security at GITAM university, Bangalore. I am very keen in full stack web development and also in fitness. 
                I have experience in react JS, next.JS, Tailwind CSS,  HTML, CSS ,JS, python, java and frameworks. 
                I am very talkative and curious person. I am determined and good at managing my time with all my tasks. I am also a convergent thinker.
                <br/>
                In my coming days, I see myself as a full stack web developer and have my own website for my workout plans, records and nutrition too. I want to create many aesthetic looking websites with superb functionalities. 
                I want to create the lifestyle which I always dreamt of. Tailor it differently 
                </p>
              </div>
              <div className='mx-auto rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96 '>
                <Image src={avatar} alt='avatar' layout='fill' objectFit='cover'/>
              </div>
            </div>
          </div>
        </section>
        <section>
          <Projects/>
        </section>
        <section>
          <Skills/>
        </section>
      </main>
    </div>
  )
}
